### PR TITLE
Upstream update

### PR DESCRIPTION
**Pull request by eddieferrer**
- Update from upstream
- Remove dependencies
- Generate new sprites

Lots of changes from upstream since this was incredibly out of date -- the files I changes/regenerated are these: 

      modified:   flags/sprite/1x1/flag-sprite-32.png
        modified:   flags/sprite/1x1/flag-sprite-32_2x.png
        modified:   flags/sprite/4x3/flag-sprite-32.png
        modified:   flags/sprite/4x3/flag-sprite-32_2x.png
        modified:   package-lock.json
        modified:   package.json
        modified:   yarn.lock

### CODE REVIEW

**Comment by mcstover** [comment]
@eddieferrer Were you able to pull this new branch into UI and verify things are looking and working properly there?

**Review by emuvente — APPROVED** [review]
Great work!

**Review by mcstover — APPROVED** [review]
So long as this is functioning properly in UI, we should be good to merge.

We'll want to monitor the docker image build and I also wanted to note that this package also shows up in the Auth0 repo package-lock file due to the Ui import there.

**Comment by eddieferrer** [comment]
Tested and working in UI after I made some modifications to package.json to control which files are exported, and the package name. 

Storybook from UI: 
Screenshot 2024-04-24 at 2 16 54 PM

**Pull request merged**
